version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: service:db
    volumes:
      - ../:/workspaces/personal
    command: sleep infinity

  db:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devcontainer
      MYSQL_USER: devcontainer
      MYSQL_PASSWORD: devcontainer
    ports:
      - 3306:3306

volumes:
  mysql:
